#!/bin/bash

set -e

CONFIG_FILE="/Users/ivanho/.config/nvim/not_vim/app_switcher.config"
SKHDRC_FILE="/Users/ivanho/.config/nvim/not_vim/.skhdrc"
START_MARKER="# START APPSWITCHER AUTOGENERATED"
END_MARKER="# END APPSWITCHER AUTOGENERATED"
SCRIPT_PATH="$HOME/.config/nvim/not_vim/app_switch.sh"

# Check if the config file exists
if [ ! -f "$CONFIG_FILE" ]; then
  echo "Error: Config file not found at $CONFIG_FILE"
  exit 1
fi

# Read the config and generate the bindings
generated_bindings=""
while IFS=' ' read -r key app_name || [ -n "$key" ]; do
  # Skip empty lines or comments
  [[ "$key" =~ ^\s*# ]] || [[ -z "$key" ]] && continue

  # Map special characters to key codes
  case "$key" in
    ",") key_code="0x2B" ;;
    ".") key_code="0x2F" ;;
    *)   key_code="$key" ;;
  esac
  
  # Handle multi-word app names that might not be quoted
  app_name_full=$(echo "$app_name" | sed 's/ /\\ /g')

  generated_bindings+="appSwitcherMode < $key_code : $SCRIPT_PATH $app_name_full;skhd -k \"escape\"\n"
done < "$CONFIG_FILE"

# Create a temporary file to build the new skhdrc content
temp_skhdrc=$(mktemp)

# Read skhdrc line by line and replace the marked section
in_section=false
found_marker=false
while IFS= read -r line; do
  if [[ "$line" == "$START_MARKER" ]]; then
    echo "$START_MARKER" >> "$temp_skhdrc"
    echo -e "$generated_bindings" >> "$temp_skhdrc"
    in_section=true
    found_marker=true
  elif [[ "$line" == "$END_MARKER" ]]; then
    echo "$END_MARKER" >> "$temp_skhdrc"
    in_section=false
  elif [ "$in_section" = false ]; then
    echo "$line" >> "$temp_skhdrc"
  fi
done < "$SKHDRC_FILE"

# If the markers were not found, append the whole block to the end of the file
if [ "$found_marker" = false ]; then
    echo "" >> "$temp_skhdrc"
    echo "$START_MARKER" >> "$temp_skhdrc"
    echo -e "$generated_bindings" >> "$temp_skhdrc"
    echo "$END_MARKER" >> "$temp_skhdrc"
fi

# Replace the original skhdrc file with the new one
mv "$temp_skhdrc" "$SKHDRC_FILE"

echo "Successfully updated $SKHDRC_FILE with app switcher shortcuts."
